# Bonus Vocabulary - 300+ words to exceed 1000 total
BONUS_VOCABULARY = {
    "Bonus Level": {
        # Common Verbs Extended
        "membaca": {"english": "to read", "pronunciation": "mem-ba-ca", "category": "verbs", "example": "Membaca buku setiap hari."},
        "menulis": {"english": "to write", "pronunciation": "me-nu-lis", "category": "verbs", "example": "Menulis surat untuk ibu."},
        "mendengar": {"english": "to hear", "pronunciation": "men-de-ngar", "category": "verbs", "example": "Mendengar musik klasik."},
        "melihat": {"english": "to see", "pronunciation": "me-li-hat", "category": "verbs", "example": "Melihat pemandangan indah."},
        "berbicara": {"english": "to speak", "pronunciation": "ber-bi-ca-ra", "category": "verbs", "example": "Berbicara dengan teman."},
        "berjalan": {"english": "to walk", "pronunciation": "ber-ja-lan", "category": "verbs", "example": "Berjalan di taman."},
        "berlari": {"english": "to run", "pronunciation": "ber-la-ri", "category": "verbs", "example": "Berlari pagi hari."},
        "melompat": {"english": "to jump", "pronunciation": "me-lom-pat", "category": "verbs", "example": "Melompat tinggi sekali."},
        "berenang": {"english": "to swim", "pronunciation": "be-re-nang", "category": "verbs", "example": "Berenang di kolam."},
        "menari": {"english": "to dance", "pronunciation": "me-na-ri", "category": "verbs", "example": "Menari dengan gembira."},
        "bernyanyi": {"english": "to sing", "pronunciation": "ber-nya-nyi", "category": "verbs", "example": "Bernyanyi lagu favorit."},
        "bermain": {"english": "to play", "pronunciation": "ber-ma-in", "category": "verbs", "example": "Bermain dengan anak-anak."},
        "bekerja": {"english": "to work", "pronunciation": "be-ker-ja", "category": "verbs", "example": "Bekerja keras setiap hari."},
        "istirahat": {"english": "to rest", "pronunciation": "is-ti-ra-hat", "category": "verbs", "example": "Istirahat setelah bekerja."},
        "bangun": {"english": "to wake up", "pronunciation": "bang-un", "category": "verbs", "example": "Bangun pagi setiap hari."},
        "tidur": {"english": "to sleep", "pronunciation": "ti-dur", "category": "verbs", "example": "Tidur nyenyak malam ini."},
        "mandi": {"english": "to bathe", "pronunciation": "man-di", "category": "verbs", "example": "Mandi air hangat."},
        "mencuci": {"english": "to wash", "pronunciation": "men-cu-ci", "category": "verbs", "example": "Mencuci pakaian kotor."},
        "memasak": {"english": "to cook", "pronunciation": "me-ma-sak", "category": "verbs", "example": "Memasak makanan lezat."},
        "membersihkan": {"english": "to clean", "pronunciation": "mem-ber-sih-kan", "category": "verbs", "example": "Membersihkan rumah setiap minggu."},
        
        # Daily Activities
        "sarapan": {"english": "breakfast", "pronunciation": "sa-ra-pan", "category": "activities", "example": "Sarapan roti dan kopi."},
        "makan siang": {"english": "lunch", "pronunciation": "ma-kan si-ang", "category": "activities", "example": "Makan siang di kantor."},
        "makan malam": {"english": "dinner", "pronunciation": "ma-kan ma-lam", "category": "activities", "example": "Makan malam bersama keluarga."},
        "berbelanja": {"english": "shopping", "pronunciation": "ber-be-lan-ja", "category": "activities", "example": "Berbelanja di pasar."},
        "berolahraga": {"english": "exercise", "pronunciation": "ber-o-lah-ra-ga", "category": "activities", "example": "Berolahraga setiap pagi."},
        "menonton": {"english": "to watch", "pronunciation": "me-non-ton", "category": "activities", "example": "Menonton film di bioskop."},
        "berkunjung": {"english": "to visit", "pronunciation": "ber-kun-jung", "category": "activities", "example": "Berkunjung ke rumah nenek."},
        "belajar": {"english": "to study", "pronunciation": "be-la-jar", "category": "activities", "example": "Belajar bahasa Indonesia."},
        "mengajar": {"english": "to teach", "pronunciation": "me-nga-jar", "category": "activities", "example": "Mengajar anak-anak."},
        "rapat": {"english": "meeting", "pronunciation": "ra-pat", "category": "activities", "example": "Rapat penting hari ini."},
        
        # Household Items
        "peralatan": {"english": "equipment", "pronunciation": "per-a-lat-an", "category": "household", "example": "Peralatan dapur lengkap."},
        "piring": {"english": "plate", "pronunciation": "pi-ring", "category": "household", "example": "Piring untuk makan."},
        "mangkuk": {"english": "bowl", "pronunciation": "mang-kuk", "category": "household", "example": "Mangkuk nasi putih."},
        "gelas": {"english": "glass", "pronunciation": "ge-las", "category": "household", "example": "Gelas air mineral."},
        "cangkir": {"english": "cup", "pronunciation": "cang-kir", "category": "household", "example": "Cangkir kopi panas."},
        "sendok": {"english": "spoon", "pronunciation": "sen-dok", "category": "household", "example": "Sendok untuk makan."},
        "garpu": {"english": "fork", "pronunciation": "gar-pu", "category": "household", "example": "Garpu dan pisau."},
        "pisau": {"english": "knife", "pronunciation": "pi-sau", "category": "household", "example": "Pisau tajam hati-hati."},
        "teko": {"english": "teapot", "pronunciation": "te-ko", "category": "household", "example": "Teko untuk teh."},
        "panci": {"english": "pot", "pronunciation": "pan-ci", "category": "household", "example": "Panci masak nasi."},
        "wajan": {"english": "pan", "pronunciation": "wa-jan", "category": "household", "example": "Wajan untuk goreng."},
        "kompor": {"english": "stove", "pronunciation": "kom-por", "category": "household", "example": "Kompor gas biru."},
        "kulkas": {"english": "refrigerator", "pronunciation": "kul-kas", "category": "household", "example": "Kulkas simpan makanan."},
        "mesin cuci": {"english": "washing machine", "pronunciation": "me-sin cu-ci", "category": "household", "example": "Mesin cuci otomatis."},
        "setrika": {"english": "iron", "pronunciation": "set-ri-ka", "category": "household", "example": "Setrika baju kerja."},
        "sapu": {"english": "broom", "pronunciation": "sa-pu", "category": "household", "example": "Sapu lantai kotor."},
        "kain pel": {"english": "mop", "pronunciation": "ka-in pel", "category": "household", "example": "Kain pel basah."},
        "ember": {"english": "bucket", "pronunciation": "em-ber", "category": "household", "example": "Ember air bersih."},
        "sikat": {"english": "brush", "pronunciation": "si-kat", "category": "household", "example": "Sikat gigi setiap hari."},
        "handuk": {"english": "towel", "pronunciation": "han-duk", "category": "household", "example": "Handuk setelah mandi."},
        
        # Clothing Extended
        "seragam": {"english": "uniform", "pronunciation": "se-ra-gam", "category": "clothing", "example": "Seragam sekolah rapi."},
        "kostum": {"english": "costume", "pronunciation": "kos-tum", "category": "clothing", "example": "Kostum pesta unik."},
        "pakaian dalam": {"english": "underwear", "pronunciation": "pa-ka-i-an da-lam", "category": "clothing", "example": "Pakaian dalam bersih."},
        "bra": {"english": "bra", "pronunciation": "bra", "category": "clothing", "example": "Bra warna putih."},
        "celana dalam": {"english": "underwear", "pronunciation": "ce-la-na da-lam", "category": "clothing", "example": "Celana dalam nyaman."},
        "kaos kaki": {"english": "socks", "pronunciation": "ka-os ka-ki", "category": "clothing", "example": "Kaos kaki tebal."},
        "stocking": {"english": "stockings", "pronunciation": "stoc-king", "category": "clothing", "example": "Stocking tipis transparan."},
        "sarung": {"english": "sarong", "pronunciation": "sa-rung", "category": "clothing", "example": "Sarung untuk sholat."},
        "kerudung": {"english": "headscarf", "pronunciation": "ke-ru-dung", "category": "clothing", "example": "Kerudung cantik warna-warni."},
        "jilbab": {"english": "hijab", "pronunciation": "jil-bab", "category": "clothing", "example": "Jilbab syar'i panjang."},
        
        # Food Extended
        "lauk": {"english": "side dish", "pronunciation": "la-uk", "category": "food", "example": "Lauk pauk lengkap."},
        "sayuran": {"english": "vegetables", "pronunciation": "sa-yu-ran", "category": "food", "example": "Sayuran hijau segar."},
        "bumbu": {"english": "spices", "pronunciation": "bum-bu", "category": "food", "example": "Bumbu dapur lengkap."},
        "sambal": {"english": "chili sauce", "pronunciation": "sam-bal", "category": "food", "example": "Sambal pedas enak."},
        "kecap": {"english": "soy sauce", "pronunciation": "ke-cap", "category": "food", "example": "Kecap manis untuk nasi."},
        "saus": {"english": "sauce", "pronunciation": "sa-us", "category": "food", "example": "Saus tomat untuk mie."},
        "mayones": {"english": "mayonnaise", "pronunciation": "ma-yo-nes", "category": "food", "example": "Mayones untuk salad."},
        "selai": {"english": "jam", "pronunciation": "se-lai", "category": "food", "example": "Selai strawberry manis."},
        "madu": {"english": "honey", "pronunciation": "ma-du", "category": "food", "example": "Madu asli dari lebah."},
        "sirup": {"english": "syrup", "pronunciation": "si-rup", "category": "food", "example": "Sirup merah segar."},
        
        # Transportation Extended
        "kendaraan": {"english": "vehicle", "pronunciation": "ken-da-ra-an", "category": "transport", "example": "Kendaraan bermotor."},
        "roda": {"english": "wheel", "pronunciation": "ro-da", "category": "transport", "example": "Roda mobil bundar."},
        "mesin": {"english": "engine", "pronunciation": "me-sin", "category": "transport", "example": "Mesin mobil rusak."},
        "bensin": {"english": "gasoline", "pronunciation": "ben-sin", "category": "transport", "example": "Bensin habis isi lagi."},
        "solar": {"english": "diesel", "pronunciation": "so-lar", "category": "transport", "example": "Solar untuk truk."},
        "oli": {"english": "oil", "pronunciation": "o-li", "category": "transport", "example": "Oli mesin perlu ganti."},
        "ban": {"english": "tire", "pronunciation": "ban", "category": "transport", "example": "Ban mobil kempes."},
        "rem": {"english": "brake", "pronunciation": "rem", "category": "transport", "example": "Rem harus berfungsi baik."},
        "klakson": {"english": "horn", "pronunciation": "klak-son", "category": "transport", "example": "Klakson berbunyi keras."},
        "lampu": {"english": "light", "pronunciation": "lam-pu", "category": "transport", "example": "Lampu depan terang."},
        
        # Nature Extended
        "pemandangan": {"english": "scenery", "pronunciation": "pe-man-dang-an", "category": "nature", "example": "Pemandangan indah sekali."},
        "udara": {"english": "air", "pronunciation": "u-da-ra", "category": "nature", "example": "Udara segar pagi hari."},
        "angin": {"english": "wind", "pronunciation": "a-ngin", "category": "nature", "example": "Angin sepoi-sepoi sejuk."},
        "cahaya": {"english": "light", "pronunciation": "ca-ha-ya", "category": "nature", "example": "Cahaya matahari terang."},
        "bayangan": {"english": "shadow", "pronunciation": "ba-yang-an", "category": "nature", "example": "Bayangan pohon panjang."},
        "suara": {"english": "sound", "pronunciation": "su-a-ra", "category": "nature", "example": "Suara burung merdu."},
        "aroma": {"english": "aroma", "pronunciation": "a-ro-ma", "category": "nature", "example": "Aroma bunga harum."},
        "rasa": {"english": "taste", "pronunciation": "ra-sa", "category": "nature", "example": "Rasa makanan enak."},
        "tekstur": {"english": "texture", "pronunciation": "teks-tur", "category": "nature", "example": "Tekstur kain halus."},
        "warna": {"english": "color", "pronunciation": "war-na", "category": "nature", "example": "Warna pelangi indah."},
        
        # Time Extended
        "detik": {"english": "second", "pronunciation": "de-tik", "category": "time", "example": "Detik berlalu cepat."},
        "menit": {"english": "minute", "pronunciation": "me-nit", "category": "time", "example": "Menit demi menit."},
        "jam": {"english": "hour", "pronunciation": "jam", "category": "time", "example": "Jam berapa sekarang?"},
        "hari": {"english": "day", "pronunciation": "ha-ri", "category": "time", "example": "Hari ini cerah."},
        "minggu": {"english": "week", "pronunciation": "ming-gu", "category": "time", "example": "Minggu depan libur."},
        "bulan": {"english": "month", "pronunciation": "bu-lan", "category": "time", "example": "Bulan ini panas."},
        "tahun": {"english": "year", "pronunciation": "ta-hun", "category": "time", "example": "Tahun baru harapan baru."},
        "abad": {"english": "century", "pronunciation": "a-bad", "category": "time", "example": "Abad ke-21 modern."},
        "masa": {"english": "era", "pronunciation": "ma-sa", "category": "time", "example": "Masa depan cerah."},
        "zaman": {"english": "era", "pronunciation": "za-man", "category": "time", "example": "Zaman dahulu sederhana."},
        
        # Directions
        "utara": {"english": "north", "pronunciation": "u-ta-ra", "category": "directions", "example": "Arah utara dingin."},
        "selatan": {"english": "south", "pronunciation": "se-la-tan", "category": "directions", "example": "Ke selatan panas."},
        "timur": {"english": "east", "pronunciation": "ti-mur", "category": "directions", "example": "Matahari terbit timur."},
        "barat": {"english": "west", "pronunciation": "ba-rat", "category": "directions", "example": "Matahari tenggelam barat."},
        "kiri": {"english": "left", "pronunciation": "ki-ri", "category": "directions", "example": "Belok ke kiri."},
        "kanan": {"english": "right", "pronunciation": "ka-nan", "category": "directions", "example": "Belok ke kanan."},
        "lurus": {"english": "straight", "pronunciation": "lu-rus", "category": "directions", "example": "Jalan lurus terus."},
        "atas": {"english": "up", "pronunciation": "a-tas", "category": "directions", "example": "Naik ke atas."},
        "bawah": {"english": "down", "pronunciation": "ba-wah", "category": "directions", "example": "Turun ke bawah."},
        "depan": {"english": "front", "pronunciation": "de-pan", "category": "directions", "example": "Di depan rumah."},
        "belakang": {"english": "back", "pronunciation": "be-la-kang", "category": "directions", "example": "Di belakang sekolah."},
        "samping": {"english": "side", "pronunciation": "sam-ping", "category": "directions", "example": "Di samping kiri."},
        "tengah": {"english": "middle", "pronunciation": "te-ngah", "category": "directions", "example": "Di tengah jalan."},
        "sudut": {"english": "corner", "pronunciation": "su-dut", "category": "directions", "example": "Di sudut jalan."},
        "ujung": {"english": "end", "pronunciation": "u-jung", "category": "directions", "example": "Di ujung jalan."},
        
        # Weather Extended
        "suhu": {"english": "temperature", "pronunciation": "su-hu", "category": "weather", "example": "Suhu hari ini tinggi."},
        "kelembaban": {"english": "humidity", "pronunciation": "ke-lem-ba-ban", "category": "weather", "example": "Kelembaban udara tinggi."},
        "tekanan": {"english": "pressure", "pronunciation": "te-ka-nan", "category": "weather", "example": "Tekanan udara rendah."},
        "kecepatan": {"english": "speed", "pronunciation": "ke-ce-pa-tan", "category": "weather", "example": "Kecepatan angin kencang."},
        "arah": {"english": "direction", "pronunciation": "a-rah", "category": "weather", "example": "Arah angin berubah."},
        "intensitas": {"english": "intensity", "pronunciation": "in-ten-si-tas", "category": "weather", "example": "Intensitas hujan tinggi."},
        "durasi": {"english": "duration", "pronunciation": "du-ra-si", "category": "weather", "example": "Durasi hujan lama."},
        "frekuensi": {"english": "frequency", "pronunciation": "fre-kuen-si", "category": "weather", "example": "Frekuensi hujan sering."},
        "prakiraan": {"english": "forecast", "pronunciation": "pra-ki-ra-an", "category": "weather", "example": "Prakiraan cuaca besok."},
        "ramalan": {"english": "prediction", "pronunciation": "ra-ma-lan", "category": "weather", "example": "Ramalan cuaca akurat."}
    }
}
