# Extended Indonesian Vocabulary Database
# This file contains 1000+ Indonesian words organized by categories

EXTENDED_VOCABULARY = {
    "Advanced": {
        # Food & Drink (100+ words)
        "nasi": {"english": "rice", "pronunciation": "na-si", "category": "food", "example": "Saya makan nasi."},
        "roti": {"english": "bread", "pronunciation": "ro-ti", "category": "food", "example": "Roti ini enak."},
        "daging": {"english": "meat", "pronunciation": "da-ging", "category": "food", "example": "Daging sapi mahal."},
        "ayam": {"english": "chicken", "pronunciation": "a-yam", "category": "food", "example": "Ayam goreng enak."},
        "ikan": {"english": "fish", "pronunciation": "i-kan", "category": "food", "example": "Ikan ini segar."},
        "telur": {"english": "egg", "pronunciation": "te-lur", "category": "food", "example": "Telur dadar untuk sarapan."},
        "susu": {"english": "milk", "pronunciation": "su-su", "category": "food", "example": "Anak minum susu."},
        "kopi": {"english": "coffee", "pronunciation": "ko-pi", "category": "food", "example": "Saya suka kopi."},
        "teh": {"english": "tea", "pronunciation": "teh", "category": "food", "example": "Teh manis enak."},
        "gula": {"english": "sugar", "pronunciation": "gu-la", "category": "food", "example": "Tambahkan gula sedikit."},
        "garam": {"english": "salt", "pronunciation": "ga-ram", "category": "food", "example": "Makanan perlu garam."},
        "sayur": {"english": "vegetables", "pronunciation": "sa-yur", "category": "food", "example": "Sayur hijau sehat."},
        "buah": {"english": "fruit", "pronunciation": "bu-ah", "category": "food", "example": "Buah-buahan segar."},
        "apel": {"english": "apple", "pronunciation": "a-pel", "category": "food", "example": "Apel merah manis."},
        "pisang": {"english": "banana", "pronunciation": "pi-sang", "category": "food", "example": "Pisang kuning matang."},
        "jeruk": {"english": "orange", "pronunciation": "je-ruk", "category": "food", "example": "Jeruk segar asam."},
        "mangga": {"english": "mango", "pronunciation": "mang-ga", "category": "food", "example": "Mangga manis sekali."},
        "anggur": {"english": "grape", "pronunciation": "ang-gur", "category": "food", "example": "Anggur hijau segar."},
        "semangka": {"english": "watermelon", "pronunciation": "se-mang-ka", "category": "food", "example": "Semangka merah manis."},
        "tomat": {"english": "tomato", "pronunciation": "to-mat", "category": "food", "example": "Tomat untuk salad."},
        "wortel": {"english": "carrot", "pronunciation": "wor-tel", "category": "food", "example": "Wortel orange sehat."},
        "kentang": {"english": "potato", "pronunciation": "ken-tang", "category": "food", "example": "Kentang goreng enak."},
        "bawang": {"english": "onion", "pronunciation": "ba-wang", "category": "food", "example": "Bawang merah pedas."},
        "cabai": {"english": "chili", "pronunciation": "ca-bai", "category": "food", "example": "Cabai merah pedas."},
        "keju": {"english": "cheese", "pronunciation": "ke-ju", "category": "food", "example": "Keju untuk roti."},
        "mentega": {"english": "butter", "pronunciation": "men-te-ga", "category": "food", "example": "Mentega untuk masak."},
        "minyak": {"english": "oil", "pronunciation": "mi-nyak", "category": "food", "example": "Minyak untuk goreng."},
        "mie": {"english": "noodles", "pronunciation": "mi-e", "category": "food", "example": "Mie ayam enak."},
        "sup": {"english": "soup", "pronunciation": "sup", "category": "food", "example": "Sup ayam hangat."},
        "salad": {"english": "salad", "pronunciation": "sa-lad", "category": "food", "example": "Salad sayur segar."},
        "kue": {"english": "cake", "pronunciation": "ku-e", "category": "food", "example": "Kue ulang tahun."},
        "es krim": {"english": "ice cream", "pronunciation": "es krim", "category": "food", "example": "Es krim vanilla dingin."},
        "cokelat": {"english": "chocolate", "pronunciation": "co-ke-lat", "category": "food", "example": "Cokelat manis enak."},
        "permen": {"english": "candy", "pronunciation": "per-men", "category": "food", "example": "Permen untuk anak."},
        "jus": {"english": "juice", "pronunciation": "jus", "category": "food", "example": "Jus jeruk segar."},
        "air putih": {"english": "water", "pronunciation": "a-ir pu-tih", "category": "food", "example": "Minum air putih sehat."},
        
        # Body Parts (50+ words)
        "badan": {"english": "body", "pronunciation": "ba-dan", "category": "body", "example": "Badan saya sehat."},
        "wajah": {"english": "face", "pronunciation": "wa-jah", "category": "body", "example": "Wajah dia cantik."},
        "rambut": {"english": "hair", "pronunciation": "ram-but", "category": "body", "example": "Rambut saya hitam."},
        "telinga": {"english": "ear", "pronunciation": "te-li-nga", "category": "body", "example": "Telinga untuk mendengar."},
        "gigi": {"english": "teeth", "pronunciation": "gi-gi", "category": "body", "example": "Gigi putih bersih."},
        "lidah": {"english": "tongue", "pronunciation": "li-dah", "category": "body", "example": "Lidah untuk bicara."},
        "leher": {"english": "neck", "pronunciation": "le-her", "category": "body", "example": "Leher saya panjang."},
        "bahu": {"english": "shoulder", "pronunciation": "ba-hu", "category": "body", "example": "Bahu kiri sakit."},
        "lengan": {"english": "arm", "pronunciation": "le-ngan", "category": "body", "example": "Lengan kanan kuat."},
        "siku": {"english": "elbow", "pronunciation": "si-ku", "category": "body", "example": "Siku bengkok sakit."},
        "pergelangan": {"english": "wrist", "pronunciation": "per-ge-lang-an", "category": "body", "example": "Pergelangan tangan kecil."},
        "jari": {"english": "finger", "pronunciation": "ja-ri", "category": "body", "example": "Jari tangan lima."},
        "kuku": {"english": "nail", "pronunciation": "ku-ku", "category": "body", "example": "Kuku panjang dipotong."},
        "dada": {"english": "chest", "pronunciation": "da-da", "category": "body", "example": "Dada lebar kuat."},
        "perut": {"english": "stomach", "pronunciation": "pe-rut", "category": "body", "example": "Perut lapar bunyi."},
        "punggung": {"english": "back", "pronunciation": "pung-gung", "category": "body", "example": "Punggung sakit duduk."},
        "pinggang": {"english": "waist", "pronunciation": "ping-gang", "category": "body", "example": "Pinggang ramping cantik."},
        "pantat": {"english": "buttocks", "pronunciation": "pan-tat", "category": "body", "example": "Duduk di kursi."},
        "paha": {"english": "thigh", "pronunciation": "pa-ha", "category": "body", "example": "Paha besar kuat."},
        "lutut": {"english": "knee", "pronunciation": "lu-tut", "category": "body", "example": "Lutut sakit jalan."},
        "betis": {"english": "calf", "pronunciation": "be-tis", "category": "body", "example": "Betis besar atletik."},
        "tumit": {"english": "heel", "pronunciation": "tu-mit", "category": "body", "example": "Tumit tinggi sepatu."},
        "jari kaki": {"english": "toe", "pronunciation": "ja-ri ka-ki", "category": "body", "example": "Jari kaki lima."},
        
        # Clothing (50+ words)
        "pakaian": {"english": "clothes", "pronunciation": "pa-ka-i-an", "category": "clothing", "example": "Pakaian bersih rapi."},
        "baju": {"english": "shirt", "pronunciation": "ba-ju", "category": "clothing", "example": "Baju putih bagus."},
        "kemeja": {"english": "dress shirt", "pronunciation": "ke-me-ja", "category": "clothing", "example": "Kemeja untuk kerja."},
        "kaos": {"english": "t-shirt", "pronunciation": "ka-os", "category": "clothing", "example": "Kaos merah nyaman."},
        "celana": {"english": "pants", "pronunciation": "ce-la-na", "category": "clothing", "example": "Celana hitam panjang."},
        "rok": {"english": "skirt", "pronunciation": "rok", "category": "clothing", "example": "Rok pendek cantik."},
        "gaun": {"english": "dress", "pronunciation": "ga-un", "category": "clothing", "example": "Gaun pesta mewah."},
        "jas": {"english": "suit jacket", "pronunciation": "jas", "category": "clothing", "example": "Jas hitam formal."},
        "jaket": {"english": "jacket", "pronunciation": "ja-ket", "category": "clothing", "example": "Jaket tebal hangat."},
        "sweater": {"english": "sweater", "pronunciation": "swe-a-ter", "category": "clothing", "example": "Sweater wol hangat."},
        "sepatu": {"english": "shoes", "pronunciation": "se-pa-tu", "category": "clothing", "example": "Sepatu kulit bagus."},
        "sandal": {"english": "sandals", "pronunciation": "san-dal", "category": "clothing", "example": "Sandal jepit nyaman."},
        "kaus kaki": {"english": "socks", "pronunciation": "ka-us ka-ki", "category": "clothing", "example": "Kaus kaki putih."},
        "topi": {"english": "hat", "pronunciation": "to-pi", "category": "clothing", "example": "Topi melindungi matahari."},
        "ikat pinggang": {"english": "belt", "pronunciation": "i-kat ping-gang", "category": "clothing", "example": "Ikat pinggang kulit."},
        "dasi": {"english": "tie", "pronunciation": "da-si", "category": "clothing", "example": "Dasi merah formal."},
        "sarung tangan": {"english": "gloves", "pronunciation": "sa-rung ta-ngan", "category": "clothing", "example": "Sarung tangan hangat."},
        "syal": {"english": "scarf", "pronunciation": "syal", "category": "clothing", "example": "Syal wol tebal."},
        "kacamata": {"english": "glasses", "pronunciation": "ka-ca-ma-ta", "category": "clothing", "example": "Kacamata untuk baca."},
        "jam tangan": {"english": "watch", "pronunciation": "jam ta-ngan", "category": "clothing", "example": "Jam tangan emas."},
        "perhiasan": {"english": "jewelry", "pronunciation": "per-hi-a-san", "category": "clothing", "example": "Perhiasan emas cantik."},
        "cincin": {"english": "ring", "pronunciation": "cin-cin", "category": "clothing", "example": "Cincin kawin emas."},
        "kalung": {"english": "necklace", "pronunciation": "ka-lung", "category": "clothing", "example": "Kalung mutiara cantik."},
        "anting": {"english": "earrings", "pronunciation": "an-ting", "category": "clothing", "example": "Anting berlian berkilau."},
        "gelang": {"english": "bracelet", "pronunciation": "ge-lang", "category": "clothing", "example": "Gelang perak indah."},
        
        # Transportation (40+ words)
        "transportasi": {"english": "transportation", "pronunciation": "trans-por-ta-si", "category": "transport", "example": "Transportasi umum murah."},
        "pesawat": {"english": "airplane", "pronunciation": "pe-sa-wat", "category": "transport", "example": "Pesawat terbang tinggi."},
        "kereta": {"english": "train", "pronunciation": "ke-re-ta", "category": "transport", "example": "Kereta api cepat."},
        "bus": {"english": "bus", "pronunciation": "bus", "category": "transport", "example": "Bus kota ramai."},
        "taksi": {"english": "taxi", "pronunciation": "tak-si", "category": "transport", "example": "Taksi online mudah."},
        "ojek": {"english": "motorcycle taxi", "pronunciation": "o-jek", "category": "transport", "example": "Ojek online cepat."},
        "becak": {"english": "rickshaw", "pronunciation": "be-cak", "category": "transport", "example": "Becak tradisional unik."},
        "kapal": {"english": "ship", "pronunciation": "ka-pal", "category": "transport", "example": "Kapal laut besar."},
        "perahu": {"english": "boat", "pronunciation": "pe-ra-hu", "category": "transport", "example": "Perahu nelayan kecil."},
        "helikopter": {"english": "helicopter", "pronunciation": "he-li-kop-ter", "category": "transport", "example": "Helikopter terbang rendah."},
        "truk": {"english": "truck", "pronunciation": "truk", "category": "transport", "example": "Truk besar angkut barang."},
        "pickup": {"english": "pickup truck", "pronunciation": "pick-up", "category": "transport", "example": "Pickup untuk kerja."},
        "van": {"english": "van", "pronunciation": "van", "category": "transport", "example": "Van untuk keluarga."},
        "ambulans": {"english": "ambulance", "pronunciation": "am-bu-lans", "category": "transport", "example": "Ambulans bawa pasien."},
        "pemadam": {"english": "fire truck", "pronunciation": "pe-ma-dam", "category": "transport", "example": "Mobil pemadam kebakaran."},
        "polisi": {"english": "police car", "pronunciation": "po-li-si", "category": "transport", "example": "Mobil polisi patroli."},
        
        # Places & Buildings (60+ words)
        "tempat": {"english": "place", "pronunciation": "tem-pat", "category": "places", "example": "Tempat ini bagus."},
        "kota": {"english": "city", "pronunciation": "ko-ta", "category": "places", "example": "Kota besar ramai."},
        "desa": {"english": "village", "pronunciation": "de-sa", "category": "places", "example": "Desa tenang sejuk."},
        "jalan": {"english": "street", "pronunciation": "ja-lan", "category": "places", "example": "Jalan raya lebar."},
        "gang": {"english": "alley", "pronunciation": "gang", "category": "places", "example": "Gang sempit gelap."},
        "taman": {"english": "park", "pronunciation": "ta-man", "category": "places", "example": "Taman kota hijau."},
        "pantai": {"english": "beach", "pronunciation": "pan-tai", "category": "places", "example": "Pantai pasir putih."},
        "gunung": {"english": "mountain", "pronunciation": "gu-nung", "category": "places", "example": "Gunung tinggi indah."},
        "sungai": {"english": "river", "pronunciation": "su-ngai", "category": "places", "example": "Sungai jernih mengalir."},
        "danau": {"english": "lake", "pronunciation": "da-nau", "category": "places", "example": "Danau tenang biru."},
        "hutan": {"english": "forest", "pronunciation": "hu-tan", "category": "places", "example": "Hutan lebat hijau."},
        "sawah": {"english": "rice field", "pronunciation": "sa-wah", "category": "places", "example": "Sawah padi hijau."},
        "kebun": {"english": "garden", "pronunciation": "ke-bun", "category": "places", "example": "Kebun bunga cantik."},
        "pasar": {"english": "market", "pronunciation": "pa-sar", "category": "places", "example": "Pasar tradisional ramai."},
        "toko": {"english": "store", "pronunciation": "to-ko", "category": "places", "example": "Toko buku lengkap."},
        "mall": {"english": "mall", "pronunciation": "mall", "category": "places", "example": "Mall besar modern."},
        "supermarket": {"english": "supermarket", "pronunciation": "su-per-mar-ket", "category": "places", "example": "Supermarket lengkap murah."},
        "restoran": {"english": "restaurant", "pronunciation": "res-to-ran", "category": "places", "example": "Restoran enak mahal."},
        "warung": {"english": "small restaurant", "pronunciation": "wa-rung", "category": "places", "example": "Warung makan murah."},
        "cafe": {"english": "cafe", "pronunciation": "ca-fe", "category": "places", "example": "Cafe kopi nyaman."},
        "hotel": {"english": "hotel", "pronunciation": "ho-tel", "category": "places", "example": "Hotel mewah mahal."},
        "penginapan": {"english": "lodging", "pronunciation": "pe-ngi-na-pan", "category": "places", "example": "Penginapan murah bersih."},
        "sekolah": {"english": "school", "pronunciation": "se-ko-lah", "category": "places", "example": "Sekolah dasar dekat."},
        "universitas": {"english": "university", "pronunciation": "u-ni-ver-si-tas", "category": "places", "example": "Universitas negeri bagus."},
        "perpustakaan": {"english": "library", "pronunciation": "per-pus-ta-ka-an", "category": "places", "example": "Perpustakaan buku banyak."},
        "rumah sakit": {"english": "hospital", "pronunciation": "ru-mah sa-kit", "category": "places", "example": "Rumah sakit besar."},
        "klinik": {"english": "clinic", "pronunciation": "kli-nik", "category": "places", "example": "Klinik dokter dekat."},
        "apotek": {"english": "pharmacy", "pronunciation": "a-po-tek", "category": "places", "example": "Apotek jual obat."},
        "bank": {"english": "bank", "pronunciation": "bank", "category": "places", "example": "Bank buka pagi."},
        "kantor": {"english": "office", "pronunciation": "kan-tor", "category": "places", "example": "Kantor kerja sibuk."},
        "pabrik": {"english": "factory", "pronunciation": "pab-rik", "category": "places", "example": "Pabrik produksi besar."},
        "stasiun": {"english": "station", "pronunciation": "sta-si-un", "category": "places", "example": "Stasiun kereta ramai."},
        "bandara": {"english": "airport", "pronunciation": "ban-da-ra", "category": "places", "example": "Bandara internasional besar."},
        "pelabuhan": {"english": "port", "pronunciation": "pe-la-bu-han", "category": "places", "example": "Pelabuhan kapal laut."},
        "terminal": {"english": "terminal", "pronunciation": "ter-mi-nal", "category": "places", "example": "Terminal bus kota."},
        "masjid": {"english": "mosque", "pronunciation": "mas-jid", "category": "places", "example": "Masjid untuk sholat."},
        "gereja": {"english": "church", "pronunciation": "ge-re-ja", "category": "places", "example": "Gereja untuk ibadah."},
        "kuil": {"english": "temple", "pronunciation": "ku-il", "category": "places", "example": "Kuil Hindu indah."},
        "museum": {"english": "museum", "pronunciation": "mu-se-um", "category": "places", "example": "Museum sejarah menarik."},
        "bioskop": {"english": "cinema", "pronunciation": "bi-os-kop", "category": "places", "example": "Bioskop film baru."},
        "gedung": {"english": "building", "pronunciation": "ge-dung", "category": "places", "example": "Gedung tinggi modern."}
    }
}
