# Mega Indonesian Vocabulary - 1000+ Words
# Additional vocabulary to reach 1000+ total words

MEGA_VOCABULARY = {
    "Intermediate Plus": {
        # More Numbers & Math
        "seratus": {"english": "one hundred", "pronunciation": "se-ra-tus", "category": "numbers", "example": "Seratus orang hadir."},
        "ribu": {"english": "thousand", "pronunciation": "ri-bu", "category": "numbers", "example": "Seribu rupiah murah."},
        "juta": {"english": "million", "pronunciation": "ju-ta", "category": "numbers", "example": "Satu juta orang."},
        "miliar": {"english": "billion", "pronunciation": "mi-li-ar", "category": "numbers", "example": "Miliar rupiah banyak."},
        "setengah": {"english": "half", "pronunciation": "se-te-ngah", "category": "numbers", "example": "Setengah jam lagi."},
        "seperempat": {"english": "quarter", "pronunciation": "se-pe-rem-pat", "category": "numbers", "example": "Seperempat bagian."},
        "pertama": {"english": "first", "pronunciation": "per-ta-ma", "category": "numbers", "example": "Anak pertama pintar."},
        "kedua": {"english": "second", "pronunciation": "ke-du-a", "category": "numbers", "example": "Rumah kedua besar."},
        "ketiga": {"english": "third", "pronunciation": "ke-ti-ga", "category": "numbers", "example": "Lantai ketiga tinggi."},
        "terakhir": {"english": "last", "pronunciation": "te-rak-hir", "category": "numbers", "example": "Hari terakhir sedih."},
        
        # Emotions & Feelings
        "senang": {"english": "happy", "pronunciation": "se-nang", "category": "emotions", "example": "Saya senang hari ini."},
        "sedih": {"english": "sad", "pronunciation": "se-dih", "category": "emotions", "example": "Dia sedih kehilangan."},
        "marah": {"english": "angry", "pronunciation": "ma-rah", "category": "emotions", "example": "Ayah marah keras."},
        "takut": {"english": "afraid", "pronunciation": "ta-kut", "category": "emotions", "example": "Anak takut gelap."},
        "cinta": {"english": "love", "pronunciation": "cin-ta", "category": "emotions", "example": "Cinta ibu tulus."},
        "benci": {"english": "hate", "pronunciation": "ben-ci", "category": "emotions", "example": "Jangan benci orang."},
        "kaget": {"english": "surprised", "pronunciation": "ka-get", "category": "emotions", "example": "Saya kaget sekali."},
        "bosan": {"english": "bored", "pronunciation": "bo-san", "category": "emotions", "example": "Anak bosan di rumah."},
        "lelah": {"english": "tired", "pronunciation": "le-lah", "category": "emotions", "example": "Pekerja lelah kerja."},
        "gugup": {"english": "nervous", "pronunciation": "gu-gup", "category": "emotions", "example": "Siswa gugup ujian."},
        "bangga": {"english": "proud", "pronunciation": "bang-ga", "category": "emotions", "example": "Orang tua bangga."},
        "malu": {"english": "embarrassed", "pronunciation": "ma-lu", "category": "emotions", "example": "Anak malu salah."},
        "iri": {"english": "jealous", "pronunciation": "i-ri", "category": "emotions", "example": "Jangan iri teman."},
        "heran": {"english": "confused", "pronunciation": "he-ran", "category": "emotions", "example": "Saya heran sekali."},
        "tenang": {"english": "calm", "pronunciation": "te-nang", "category": "emotions", "example": "Hati tenang damai."},
        
        # Weather & Seasons
        "musim": {"english": "season", "pronunciation": "mu-sim", "category": "weather", "example": "Musim hujan datang."},
        "kemarau": {"english": "dry season", "pronunciation": "ke-ma-rau", "category": "weather", "example": "Musim kemarau panas."},
        "semi": {"english": "spring", "pronunciation": "se-mi", "category": "weather", "example": "Musim semi bunga."},
        "panas": {"english": "summer", "pronunciation": "pa-nas", "category": "weather", "example": "Musim panas terik."},
        "gugur": {"english": "autumn", "pronunciation": "gu-gur", "category": "weather", "example": "Musim gugur daun."},
        "dingin": {"english": "winter", "pronunciation": "ding-in", "category": "weather", "example": "Musim dingin salju."},
        "cerah": {"english": "sunny", "pronunciation": "ce-rah", "category": "weather", "example": "Hari cerah terang."},
        "mendung": {"english": "cloudy", "pronunciation": "men-dung", "category": "weather", "example": "Langit mendung gelap."},
        "gerimis": {"english": "drizzle", "pronunciation": "ge-ri-mis", "category": "weather", "example": "Hujan gerimis halus."},
        "lebat": {"english": "heavy rain", "pronunciation": "le-bat", "category": "weather", "example": "Hujan lebat deras."},
        
        # School & Education
        "pendidikan": {"english": "education", "pronunciation": "pen-di-di-kan", "category": "education", "example": "Pendidikan penting sekali."},
        "belajar": {"english": "to study", "pronunciation": "be-la-jar", "category": "education", "example": "Anak belajar rajin."},
        "mengajar": {"english": "to teach", "pronunciation": "me-nga-jar", "category": "education", "example": "Guru mengajar baik."},
        "murid": {"english": "student", "pronunciation": "mu-rid", "category": "education", "example": "Murid pintar belajar."},
        "siswa": {"english": "pupil", "pronunciation": "sis-wa", "category": "education", "example": "Siswa sekolah dasar."},
        "mahasiswa": {"english": "university student", "pronunciation": "ma-ha-sis-wa", "category": "education", "example": "Mahasiswa kuliah rajin."},
        "kelas": {"english": "class", "pronunciation": "ke-las", "category": "education", "example": "Kelas satu bersih."},
        "pelajaran": {"english": "lesson", "pronunciation": "pe-la-ja-ran", "category": "education", "example": "Pelajaran matematika sulit."},
        "ujian": {"english": "exam", "pronunciation": "u-ji-an", "category": "education", "example": "Ujian besok penting."},
        "nilai": {"english": "grade", "pronunciation": "ni-lai", "category": "education", "example": "Nilai bagus senang."},
        "rapor": {"english": "report card", "pronunciation": "ra-por", "category": "education", "example": "Rapor semester baik."},
        "tugas": {"english": "homework", "pronunciation": "tu-gas", "category": "education", "example": "Tugas sekolah banyak."},
        "pr": {"english": "homework", "pronunciation": "pe-er", "category": "education", "example": "PR dikerjakan rumah."},
        "papan tulis": {"english": "blackboard", "pronunciation": "pa-pan tu-lis", "category": "education", "example": "Papan tulis hijau."},
        "kapur": {"english": "chalk", "pronunciation": "ka-pur", "category": "education", "example": "Kapur tulis putih."},
        "penghapus": {"english": "eraser", "pronunciation": "peng-ha-pus", "category": "education", "example": "Penghapus hapus salah."},
        "pensil": {"english": "pencil", "pronunciation": "pen-sil", "category": "education", "example": "Pensil tulis halus."},
        "pulpen": {"english": "pen", "pronunciation": "pul-pen", "category": "education", "example": "Pulpen tinta biru."},
        "penggaris": {"english": "ruler", "pronunciation": "peng-ga-ris", "category": "education", "example": "Penggaris ukur garis."},
        "tas": {"english": "bag", "pronunciation": "tas", "category": "education", "example": "Tas sekolah berat."},
        
        # Health & Medicine
        "kesehatan": {"english": "health", "pronunciation": "ke-se-ha-tan", "category": "health", "example": "Kesehatan penting sekali."},
        "sakit": {"english": "sick", "pronunciation": "sa-kit", "category": "health", "example": "Anak sakit demam."},
        "sehat": {"english": "healthy", "pronunciation": "se-hat", "category": "health", "example": "Badan sehat kuat."},
        "penyakit": {"english": "disease", "pronunciation": "pe-nya-kit", "category": "health", "example": "Penyakit berbahaya menular."},
        "obat": {"english": "medicine", "pronunciation": "o-bat", "category": "health", "example": "Obat diminum teratur."},
        "dokter": {"english": "doctor", "pronunciation": "dok-ter", "category": "health", "example": "Dokter periksa pasien."},
        "perawat": {"english": "nurse", "pronunciation": "pe-ra-wat", "category": "health", "example": "Perawat rawat sakit."},
        "pasien": {"english": "patient", "pronunciation": "pa-si-en", "category": "health", "example": "Pasien butuh istirahat."},
        "demam": {"english": "fever", "pronunciation": "de-mam", "category": "health", "example": "Demam tinggi bahaya."},
        "batuk": {"english": "cough", "pronunciation": "ba-tuk", "category": "health", "example": "Batuk tidak berhenti."},
        "pilek": {"english": "cold", "pronunciation": "pi-lek", "category": "health", "example": "Pilek hidung tersumbat."},
        "flu": {"english": "flu", "pronunciation": "flu", "category": "health", "example": "Flu musim hujan."},
        "sakit kepala": {"english": "headache", "pronunciation": "sa-kit ke-pa-la", "category": "health", "example": "Sakit kepala berat."},
        "sakit gigi": {"english": "toothache", "pronunciation": "sa-kit gi-gi", "category": "health", "example": "Sakit gigi ngilu."},
        "sakit perut": {"english": "stomachache", "pronunciation": "sa-kit pe-rut", "category": "health", "example": "Sakit perut mulas."},
        "luka": {"english": "wound", "pronunciation": "lu-ka", "category": "health", "example": "Luka berdarah perih."},
        "darah": {"english": "blood", "pronunciation": "da-rah", "category": "health", "example": "Darah merah mengalir."},
        "jantung": {"english": "heart", "pronunciation": "jan-tung", "category": "health", "example": "Jantung berdetak kencang."},
        "paru-paru": {"english": "lungs", "pronunciation": "pa-ru pa-ru", "category": "health", "example": "Paru-paru organ nafas."},
        "hati": {"english": "liver", "pronunciation": "ha-ti", "category": "health", "example": "Hati organ penting."},
        
        # Jobs & Professions
        "profesi": {"english": "profession", "pronunciation": "pro-fe-si", "category": "jobs", "example": "Profesi mulia guru."},
        "pekerjaan": {"english": "job", "pronunciation": "pe-ker-ja-an", "category": "jobs", "example": "Pekerjaan keras susah."},
        "karyawan": {"english": "employee", "pronunciation": "kar-ya-wan", "category": "jobs", "example": "Karyawan rajin bekerja."},
        "bos": {"english": "boss", "pronunciation": "bos", "category": "jobs", "example": "Bos pimpin perusahaan."},
        "manajer": {"english": "manager", "pronunciation": "ma-na-jer", "category": "jobs", "example": "Manajer atur kerja."},
        "sekretaris": {"english": "secretary", "pronunciation": "sek-re-ta-ris", "category": "jobs", "example": "Sekretaris catat rapat."},
        "akuntan": {"english": "accountant", "pronunciation": "a-kun-tan", "category": "jobs", "example": "Akuntan hitung uang."},
        "insinyur": {"english": "engineer", "pronunciation": "in-si-nyur", "category": "jobs", "example": "Insinyur buat jembatan."},
        "arsitek": {"english": "architect", "pronunciation": "ar-si-tek", "category": "jobs", "example": "Arsitek rancang rumah."},
        "pengacara": {"english": "lawyer", "pronunciation": "peng-a-ca-ra", "category": "jobs", "example": "Pengacara bela klien."},
        "hakim": {"english": "judge", "pronunciation": "ha-kim", "category": "jobs", "example": "Hakim putus perkara."},
        "polisi": {"english": "police", "pronunciation": "po-li-si", "category": "jobs", "example": "Polisi jaga keamanan."},
        "tentara": {"english": "soldier", "pronunciation": "ten-ta-ra", "category": "jobs", "example": "Tentara bela negara."},
        "pilot": {"english": "pilot", "pronunciation": "pi-lot", "category": "jobs", "example": "Pilot terbang pesawat."},
        "maskapai": {"english": "airline", "pronunciation": "mas-ka-pai", "category": "jobs", "example": "Maskapai penerbangan."},
        "sopir": {"english": "driver", "pronunciation": "so-pir", "category": "jobs", "example": "Sopir bawa mobil."},
        "tukang": {"english": "craftsman", "pronunciation": "tu-kang", "category": "jobs", "example": "Tukang kayu ahli."},
        "petani": {"english": "farmer", "pronunciation": "pe-ta-ni", "category": "jobs", "example": "Petani tanam padi."},
        "nelayan": {"english": "fisherman", "pronunciation": "ne-la-yan", "category": "jobs", "example": "Nelayan tangkap ikan."},
        "pedagang": {"english": "trader", "pronunciation": "pe-da-gang", "category": "jobs", "example": "Pedagang jual barang."},
        "penjual": {"english": "seller", "pronunciation": "pen-ju-al", "category": "jobs", "example": "Penjual ramah pembeli."},
        "pembeli": {"english": "buyer", "pronunciation": "pem-be-li", "category": "jobs", "example": "Pembeli pilih barang."},
        "pelayan": {"english": "waiter", "pronunciation": "pe-la-yan", "category": "jobs", "example": "Pelayan antar makanan."},
        "koki": {"english": "chef", "pronunciation": "ko-ki", "category": "jobs", "example": "Koki masak enak."},
        "tukang kebun": {"english": "gardener", "pronunciation": "tu-kang ke-bun", "category": "jobs", "example": "Tukang kebun rawat tanaman."},
        
        # Shopping & Money
        "belanja": {"english": "shopping", "pronunciation": "be-lan-ja", "category": "shopping", "example": "Belanja ke pasar."},
        "beli": {"english": "buy", "pronunciation": "be-li", "category": "shopping", "example": "Beli baju baru."},
        "jual": {"english": "sell", "pronunciation": "ju-al", "category": "shopping", "example": "Jual rumah lama."},
        "harga": {"english": "price", "pronunciation": "har-ga", "category": "shopping", "example": "Harga mahal sekali."},
        "diskon": {"english": "discount", "pronunciation": "dis-kon", "category": "shopping", "example": "Diskon besar hari ini."},
        "gratis": {"english": "free", "pronunciation": "gra-tis", "category": "shopping", "example": "Dapat hadiah gratis."},
        "bayar": {"english": "pay", "pronunciation": "ba-yar", "category": "shopping", "example": "Bayar di kasir."},
        "kembalian": {"english": "change", "pronunciation": "kem-ba-li-an", "category": "shopping", "example": "Kembalian lima ribu."},
        "kasir": {"english": "cashier", "pronunciation": "ka-sir", "category": "shopping", "example": "Kasir hitung uang."},
        "bon": {"english": "receipt", "pronunciation": "bon", "category": "shopping", "example": "Simpan bon belanja."},
        "kartu kredit": {"english": "credit card", "pronunciation": "kar-tu kre-dit", "category": "shopping", "example": "Bayar kartu kredit."},
        "tunai": {"english": "cash", "pronunciation": "tu-nai", "category": "shopping", "example": "Bayar tunai saja."},
        "atm": {"english": "ATM", "pronunciation": "a-te-em", "category": "shopping", "example": "Ambil uang di ATM."},
        "tabungan": {"english": "savings", "pronunciation": "ta-bu-ngan", "category": "shopping", "example": "Tabungan untuk masa depan."},
        "pinjaman": {"english": "loan", "pronunciation": "pin-ja-man", "category": "shopping", "example": "Pinjaman bank besar."},
        "hutang": {"english": "debt", "pronunciation": "hu-tang", "category": "shopping", "example": "Hutang harus dibayar."},
        "kaya": {"english": "rich", "pronunciation": "ka-ya", "category": "shopping", "example": "Orang kaya dermawan."},
        "miskin": {"english": "poor", "pronunciation": "mis-kin", "category": "shopping", "example": "Membantu orang miskin."},
        "hemat": {"english": "economical", "pronunciation": "he-mat", "category": "shopping", "example": "Hidup hemat bijak."},
        "boros": {"english": "wasteful", "pronunciation": "bo-ros", "category": "shopping", "example": "Jangan boros uang."},
    }
}
