# Ultimate Indonesian Vocabulary - Additional 600+ words to reach 1000+
# Advanced categories for comprehensive learning

ULTIMATE_VOCABULARY = {
    "Expert Level 1": {
        # Technology Advanced
        "perangkat lunak": {"english": "software", "pronunciation": "pe-rang-kat lu-nak", "category": "technology", "example": "Perangkat lunak komputer."},
        "perangkat keras": {"english": "hardware", "pronunciation": "pe-rang-kat ke-ras", "category": "technology", "example": "Perangkat keras rusak."},
        "sistem operasi": {"english": "operating system", "pronunciation": "sis-tem o-pe-ra-si", "category": "technology", "example": "Sistem operasi Windows."},
        "basis data": {"english": "database", "pronunciation": "ba-sis da-ta", "category": "technology", "example": "Basis data pelanggan."},
        "jaringan": {"english": "network", "pronunciation": "ja-ring-an", "category": "technology", "example": "Jaringan internet cepat."},
        "server": {"english": "server", "pronunciation": "ser-ver", "category": "technology", "example": "Server down maintenance."},
        "backup": {"english": "backup", "pronunciation": "back-up", "category": "technology", "example": "Backup data penting."},
        "virus": {"english": "computer virus", "pronunciation": "vi-rus", "category": "technology", "example": "Virus komputer berbahaya."},
        "antivirus": {"english": "antivirus", "pronunciation": "an-ti-vi-rus", "category": "technology", "example": "Antivirus melindungi komputer."},
        "firewall": {"english": "firewall", "pronunciation": "fi-re-wall", "category": "technology", "example": "Firewall blokir hacker."},
        "hacker": {"english": "hacker", "pronunciation": "hac-ker", "category": "technology", "example": "Hacker masuk sistem."},
        "password": {"english": "password", "pronunciation": "pass-word", "category": "technology", "example": "Password harus kuat."},
        "login": {"english": "login", "pronunciation": "lo-gin", "category": "technology", "example": "Login ke akun."},
        "logout": {"english": "logout", "pronunciation": "log-out", "category": "technology", "example": "Logout setelah selesai."},
        "download": {"english": "download", "pronunciation": "down-load", "category": "technology", "example": "Download file besar."},
        "upload": {"english": "upload", "pronunciation": "up-load", "category": "technology", "example": "Upload foto baru."},
        "streaming": {"english": "streaming", "pronunciation": "strea-ming", "category": "technology", "example": "Streaming video online."},
        "cloud": {"english": "cloud computing", "pronunciation": "cloud", "category": "technology", "example": "Simpan di cloud."},
        "artificial intelligence": {"english": "AI", "pronunciation": "ar-ti-fi-sial in-tel-li-gen-ce", "category": "technology", "example": "AI teknologi masa depan."},
        "robot": {"english": "robot", "pronunciation": "ro-bot", "category": "technology", "example": "Robot bantu manusia."},
        
        # Business & Economics
        "bisnis": {"english": "business", "pronunciation": "bis-nis", "category": "business", "example": "Bisnis online berkembang."},
        "ekonomi": {"english": "economy", "pronunciation": "e-ko-no-mi", "category": "business", "example": "Ekonomi negara stabil."},
        "investasi": {"english": "investment", "pronunciation": "in-ves-ta-si", "category": "business", "example": "Investasi jangka panjang."},
        "saham": {"english": "stock", "pronunciation": "sa-ham", "category": "business", "example": "Saham naik turun."},
        "obligasi": {"english": "bond", "pronunciation": "o-bli-ga-si", "category": "business", "example": "Obligasi pemerintah aman."},
        "dividen": {"english": "dividend", "pronunciation": "di-vi-den", "category": "business", "example": "Dividen dibayar tahunan."},
        "laba": {"english": "profit", "pronunciation": "la-ba", "category": "business", "example": "Laba perusahaan besar."},
        "rugi": {"english": "loss", "pronunciation": "ru-gi", "category": "business", "example": "Rugi karena salah strategi."},
        "modal": {"english": "capital", "pronunciation": "mo-dal", "category": "business", "example": "Modal usaha terbatas."},
        "kredit": {"english": "credit", "pronunciation": "kre-dit", "category": "business", "example": "Kredit bank mudah."},
        "debit": {"english": "debit", "pronunciation": "de-bit", "category": "business", "example": "Kartu debit praktis."},
        "bunga": {"english": "interest", "pronunciation": "bu-nga", "category": "business", "example": "Bunga bank tinggi."},
        "inflasi": {"english": "inflation", "pronunciation": "in-fla-si", "category": "business", "example": "Inflasi naik harga."},
        "deflasi": {"english": "deflation", "pronunciation": "def-la-si", "category": "business", "example": "Deflasi turun harga."},
        "pajak": {"english": "tax", "pronunciation": "pa-jak", "category": "business", "example": "Pajak wajib dibayar."},
        "ekspor": {"english": "export", "pronunciation": "eks-por", "category": "business", "example": "Ekspor ke luar negeri."},
        "impor": {"english": "import", "pronunciation": "im-por", "category": "business", "example": "Impor barang mewah."},
        "perdagangan": {"english": "trade", "pronunciation": "per-da-gang-an", "category": "business", "example": "Perdagangan internasional."},
        "pasar": {"english": "market", "pronunciation": "pa-sar", "category": "business", "example": "Pasar saham volatile."},
        "konsumen": {"english": "consumer", "pronunciation": "kon-su-men", "category": "business", "example": "Konsumen butuh kualitas."},
        
        # Science & Research
        "sains": {"english": "science", "pronunciation": "sa-ins", "category": "science", "example": "Sains memajukan peradaban."},
        "penelitian": {"english": "research", "pronunciation": "pe-ne-li-ti-an", "category": "science", "example": "Penelitian membutuhkan waktu."},
        "eksperimen": {"english": "experiment", "pronunciation": "eks-pe-ri-men", "category": "science", "example": "Eksperimen laboratorium."},
        "hipotesis": {"english": "hypothesis", "pronunciation": "hi-po-te-sis", "category": "science", "example": "Hipotesis perlu dibuktikan."},
        "teori": {"english": "theory", "pronunciation": "te-o-ri", "category": "science", "example": "Teori Einstein terkenal."},
        "fakta": {"english": "fact", "pronunciation": "fak-ta", "category": "science", "example": "Fakta tidak bisa dibantah."},
        "data": {"english": "data", "pronunciation": "da-ta", "category": "science", "example": "Data penelitian akurat."},
        "statistik": {"english": "statistics", "pronunciation": "sta-tis-tik", "category": "science", "example": "Statistik menunjukkan tren."},
        "analisis": {"english": "analysis", "pronunciation": "a-na-li-sis", "category": "science", "example": "Analisis mendalam diperlukan."},
        "sintesis": {"english": "synthesis", "pronunciation": "sin-te-sis", "category": "science", "example": "Sintesis berbagai sumber."},
        "metodologi": {"english": "methodology", "pronunciation": "me-to-do-lo-gi", "category": "science", "example": "Metodologi penelitian baik."},
        "variabel": {"english": "variable", "pronunciation": "va-ri-a-bel", "category": "science", "example": "Variabel bebas terikat."},
        "konstanta": {"english": "constant", "pronunciation": "kon-stan-ta", "category": "science", "example": "Konstanta tidak berubah."},
        "formula": {"english": "formula", "pronunciation": "for-mu-la", "category": "science", "example": "Formula matematika rumit."},
        "algoritma": {"english": "algorithm", "pronunciation": "al-go-rit-ma", "category": "science", "example": "Algoritma komputer pintar."},
        "genetik": {"english": "genetics", "pronunciation": "ge-ne-tik", "category": "science", "example": "Genetik turun temurun."},
        "evolusi": {"english": "evolution", "pronunciation": "e-vo-lu-si", "category": "science", "example": "Evolusi makhluk hidup."},
        "atom": {"english": "atom", "pronunciation": "a-tom", "category": "science", "example": "Atom partikel terkecil."},
        "molekul": {"english": "molecule", "pronunciation": "mo-le-kul", "category": "science", "example": "Molekul air H2O."},
        "energi": {"english": "energy", "pronunciation": "e-ner-gi", "category": "science", "example": "Energi tidak dapat musnah."},
        
        # Geography & Environment
        "geografi": {"english": "geography", "pronunciation": "ge-o-gra-fi", "category": "geography", "example": "Geografi Indonesia luas."},
        "benua": {"english": "continent", "pronunciation": "be-nu-a", "category": "geography", "example": "Benua Asia terbesar."},
        "samudra": {"english": "ocean", "pronunciation": "sa-mud-ra", "category": "geography", "example": "Samudra Pasifik luas."},
        "selat": {"english": "strait", "pronunciation": "se-lat", "category": "geography", "example": "Selat Sunda sempit."},
        "teluk": {"english": "bay", "pronunciation": "te-luk", "category": "geography", "example": "Teluk Jakarta indah."},
        "pulau": {"english": "island", "pronunciation": "pu-lau", "category": "geography", "example": "Pulau Bali terkenal."},
        "semenanjung": {"english": "peninsula", "pronunciation": "se-me-nan-jung", "category": "geography", "example": "Semenanjung Malaysia."},
        "dataran": {"english": "plain", "pronunciation": "da-ta-ran", "category": "geography", "example": "Dataran tinggi sejuk."},
        "lembah": {"english": "valley", "pronunciation": "lem-bah", "category": "geography", "example": "Lembah hijau subur."},
        "jurang": {"english": "canyon", "pronunciation": "ju-rang", "category": "geography", "example": "Jurang dalam berbahaya."},
        "gua": {"english": "cave", "pronunciation": "gu-a", "category": "geography", "example": "Gua gelap dingin."},
        "air terjun": {"english": "waterfall", "pronunciation": "a-ir ter-jun", "category": "geography", "example": "Air terjun tinggi indah."},
        "rawa": {"english": "swamp", "pronunciation": "ra-wa", "category": "geography", "example": "Rawa banyak nyamuk."},
        "padang pasir": {"english": "desert", "pronunciation": "pa-dang pa-sir", "category": "geography", "example": "Padang pasir panas."},
        "kutub": {"english": "pole", "pronunciation": "ku-tub", "category": "geography", "example": "Kutub utara dingin."},
        "khatulistiwa": {"english": "equator", "pronunciation": "kha-tu-lis-ti-wa", "category": "geography", "example": "Indonesia di khatulistiwa."},
        "iklim": {"english": "climate", "pronunciation": "ik-lim", "category": "geography", "example": "Iklim tropis hangat."},
        "lingkungan": {"english": "environment", "pronunciation": "ling-kung-an", "category": "geography", "example": "Lingkungan harus dijaga."},
        "polusi": {"english": "pollution", "pronunciation": "po-lu-si", "category": "geography", "example": "Polusi udara berbahaya."},
        "daur ulang": {"english": "recycling", "pronunciation": "da-ur u-lang", "category": "geography", "example": "Daur ulang sampah."},
        
        # Culture & Society
        "budaya": {"english": "culture", "pronunciation": "bu-da-ya", "category": "culture", "example": "Budaya Indonesia beragam."},
        "tradisi": {"english": "tradition", "pronunciation": "tra-di-si", "category": "culture", "example": "Tradisi nenek moyang."},
        "adat": {"english": "custom", "pronunciation": "a-dat", "category": "culture", "example": "Adat istiadat daerah."},
        "upacara": {"english": "ceremony", "pronunciation": "u-pa-ca-ra", "category": "culture", "example": "Upacara pernikahan."},
        "festival": {"english": "festival", "pronunciation": "fes-ti-val", "category": "culture", "example": "Festival budaya tahunan."},
        "perayaan": {"english": "celebration", "pronunciation": "pe-ra-ya-an", "category": "culture", "example": "Perayaan kemerdekaan."},
        "masyarakat": {"english": "society", "pronunciation": "ma-sya-ra-kat", "category": "culture", "example": "Masyarakat modern."},
        "komunitas": {"english": "community", "pronunciation": "ko-mu-ni-tas", "category": "culture", "example": "Komunitas peduli lingkungan."},
        "organisasi": {"english": "organization", "pronunciation": "or-ga-ni-sa-si", "category": "culture", "example": "Organisasi sosial."},
        "yayasan": {"english": "foundation", "pronunciation": "ya-ya-san", "category": "culture", "example": "Yayasan anak yatim."},
        "relawan": {"english": "volunteer", "pronunciation": "re-la-wan", "category": "culture", "example": "Relawan bencana alam."},
        "donor": {"english": "donor", "pronunciation": "do-nor", "category": "culture", "example": "Donor darah mulia."},
        "solidaritas": {"english": "solidarity", "pronunciation": "so-li-da-ri-tas", "category": "culture", "example": "Solidaritas antar warga."},
        "toleransi": {"english": "tolerance", "pronunciation": "to-le-ran-si", "category": "culture", "example": "Toleransi beragama."},
        "keragaman": {"english": "diversity", "pronunciation": "ke-ra-ga-man", "category": "culture", "example": "Keragaman budaya."},
        "persatuan": {"english": "unity", "pronunciation": "per-sa-tu-an", "category": "culture", "example": "Persatuan dalam perbedaan."},
        "gotong royong": {"english": "mutual cooperation", "pronunciation": "go-tong ro-yong", "category": "culture", "example": "Gotong royong membangun."},
        "musyawarah": {"english": "deliberation", "pronunciation": "mu-sya-wa-rah", "category": "culture", "example": "Musyawarah mencapai mufakat."},
        "mufakat": {"english": "consensus", "pronunciation": "mu-fa-kat", "category": "culture", "example": "Mufakat hasil diskusi."},
        "demokrasi": {"english": "democracy", "pronunciation": "de-mo-kra-si", "category": "culture", "example": "Demokrasi hak rakyat."},
        
        # Law & Government
        "hukum": {"english": "law", "pronunciation": "hu-kum", "category": "government", "example": "Hukum harus ditaati."},
        "undang-undang": {"english": "legislation", "pronunciation": "un-dang un-dang", "category": "government", "example": "Undang-undang dasar."},
        "peraturan": {"english": "regulation", "pronunciation": "pe-ra-tu-ran", "category": "government", "example": "Peraturan lalu lintas."},
        "pemerintah": {"english": "government", "pronunciation": "pe-me-rin-tah", "category": "government", "example": "Pemerintah melayani rakyat."},
        "presiden": {"english": "president", "pronunciation": "pre-si-den", "category": "government", "example": "Presiden kepala negara."},
        "menteri": {"english": "minister", "pronunciation": "men-te-ri", "category": "government", "example": "Menteri pendidikan."},
        "gubernur": {"english": "governor", "pronunciation": "gu-ber-nur", "category": "government", "example": "Gubernur kepala daerah."},
        "bupati": {"english": "regent", "pronunciation": "bu-pa-ti", "category": "government", "example": "Bupati pimpin kabupaten."},
        "walikota": {"english": "mayor", "pronunciation": "wa-li-ko-ta", "category": "government", "example": "Walikota pimpin kota."},
        "dpr": {"english": "parliament", "pronunciation": "de-pe-er", "category": "government", "example": "DPR buat undang-undang."},
        "pemilihan": {"english": "election", "pronunciation": "pe-mi-li-han", "category": "government", "example": "Pemilihan umum demokratis."},
        "kampanye": {"english": "campaign", "pronunciation": "kam-pa-nye", "category": "government", "example": "Kampanye politik damai."},
        "partai": {"english": "political party", "pronunciation": "par-tai", "category": "government", "example": "Partai politik banyak."},
        "korupsi": {"english": "corruption", "pronunciation": "ko-rup-si", "category": "government", "example": "Korupsi merugikan negara."},
        "transparansi": {"english": "transparency", "pronunciation": "trans-pa-ran-si", "category": "government", "example": "Transparansi pemerintahan."},
        "akuntabilitas": {"english": "accountability", "pronunciation": "a-kun-ta-bi-li-tas", "category": "government", "example": "Akuntabilitas publik."},
        "reformasi": {"english": "reform", "pronunciation": "re-for-ma-si", "category": "government", "example": "Reformasi sistem hukum."},
        "konstitusi": {"english": "constitution", "pronunciation": "kon-sti-tu-si", "category": "government", "example": "Konstitusi negara."},
        "kedaulatan": {"english": "sovereignty", "pronunciation": "ke-da-u-lat-an", "category": "government", "example": "Kedaulatan rakyat."},
        "kemerdekaan": {"english": "independence", "pronunciation": "ke-mer-de-ka-an", "category": "government", "example": "Kemerdekaan Indonesia."}
    },
    
    "Expert Level 2": {
        # Philosophy & Abstract Concepts
        "filsafat": {"english": "philosophy", "pronunciation": "fil-sa-fat", "category": "philosophy", "example": "Filsafat hidup penting."},
        "kebijaksanaan": {"english": "wisdom", "pronunciation": "ke-bi-jak-sa-na-an", "category": "philosophy", "example": "Kebijaksanaan dari pengalaman."},
        "kebenaran": {"english": "truth", "pronunciation": "ke-be-na-ran", "category": "philosophy", "example": "Kebenaran akan terungkap."},
        "keadilan": {"english": "justice", "pronunciation": "ke-a-di-lan", "category": "philosophy", "example": "Keadilan untuk semua."},
        "kebebasan": {"english": "freedom", "pronunciation": "ke-be-ba-san", "category": "philosophy", "example": "Kebebasan berpendapat."},
        "tanggung jawab": {"english": "responsibility", "pronunciation": "tang-gung ja-wab", "category": "philosophy", "example": "Tanggung jawab moral."},
        "etika": {"english": "ethics", "pronunciation": "e-ti-ka", "category": "philosophy", "example": "Etika profesi dokter."},
        "moral": {"english": "morality", "pronunciation": "mo-ral", "category": "philosophy", "example": "Moral yang baik."},
        "nilai": {"english": "value", "pronunciation": "ni-lai", "category": "philosophy", "example": "Nilai-nilai kehidupan."},
        "prinsip": {"english": "principle", "pronunciation": "prin-sip", "category": "philosophy", "example": "Prinsip hidup teguh."},
        "idealisme": {"english": "idealism", "pronunciation": "i-de-a-lis-me", "category": "philosophy", "example": "Idealisme anak muda."},
        "realisme": {"english": "realism", "pronunciation": "re-a-lis-me", "category": "philosophy", "example": "Realisme dalam hidup."},
        "eksistensialisme": {"english": "existentialism", "pronunciation": "ek-sis-ten-si-a-lis-me", "category": "philosophy", "example": "Eksistensialisme modern."},
        "materialisme": {"english": "materialism", "pronunciation": "ma-te-ri-a-lis-me", "category": "philosophy", "example": "Materialisme konsumerisme."},
        "spiritualisme": {"english": "spiritualism", "pronunciation": "spi-ri-tu-a-lis-me", "category": "philosophy", "example": "Spiritualisme keagamaan."},
        
        # Advanced Emotions & Psychology
        "psikologi": {"english": "psychology", "pronunciation": "psi-ko-lo-gi", "category": "psychology", "example": "Psikologi anak berbeda."},
        "kepribadian": {"english": "personality", "pronunciation": "ke-pri-ba-di-an", "category": "psychology", "example": "Kepribadian unik setiap orang."},
        "karakter": {"english": "character", "pronunciation": "ka-rak-ter", "category": "psychology", "example": "Karakter terbentuk pengalaman."},
        "temperamen": {"english": "temperament", "pronunciation": "tem-pe-ra-men", "category": "psychology", "example": "Temperamen bawaan lahir."},
        "motivasi": {"english": "motivation", "pronunciation": "mo-ti-va-si", "category": "psychology", "example": "Motivasi tinggi sukses."},
        "inspirasi": {"english": "inspiration", "pronunciation": "in-spi-ra-si", "category": "psychology", "example": "Inspirasi dari tokoh."},
        "aspirasi": {"english": "aspiration", "pronunciation": "as-pi-ra-si", "category": "psychology", "example": "Aspirasi menjadi dokter."},
        "ambisi": {"english": "ambition", "pronunciation": "am-bi-si", "category": "psychology", "example": "Ambisi yang sehat."},
        "dedikasi": {"english": "dedication", "pronunciation": "de-di-ka-si", "category": "psychology", "example": "Dedikasi tinggi kerja."},
        "komitmen": {"english": "commitment", "pronunciation": "ko-mit-men", "category": "psychology", "example": "Komitmen dalam hubungan."},
        "konsistensi": {"english": "consistency", "pronunciation": "kon-sis-ten-si", "category": "psychology", "example": "Konsistensi mencapai tujuan."},
        "ketekunan": {"english": "perseverance", "pronunciation": "ke-te-ku-nan", "category": "psychology", "example": "Ketekunan kunci sukses."},
        "kesabaran": {"english": "patience", "pronunciation": "ke-sa-ba-ran", "category": "psychology", "example": "Kesabaran itu indah."},
        "keberanian": {"english": "courage", "pronunciation": "ke-be-ra-ni-an", "category": "psychology", "example": "Keberanian hadapi tantangan."},
        "kepercayaan diri": {"english": "self-confidence", "pronunciation": "ke-per-ca-ya-an di-ri", "category": "psychology", "example": "Kepercayaan diri penting."},
        "harga diri": {"english": "self-esteem", "pronunciation": "har-ga di-ri", "category": "psychology", "example": "Harga diri tinggi."},
        "kerendahan hati": {"english": "humility", "pronunciation": "ke-ren-da-han ha-ti", "category": "psychology", "example": "Kerendahan hati terpuji."},
        "empati": {"english": "empathy", "pronunciation": "em-pa-ti", "category": "psychology", "example": "Empati terhadap sesama."},
        "simpati": {"english": "sympathy", "pronunciation": "sim-pa-ti", "category": "psychology", "example": "Simpati pada korban."},
        "antipati": {"english": "antipathy", "pronunciation": "an-ti-pa-ti", "category": "psychology", "example": "Antipati tanpa alasan."},
        
        # Advanced Medical Terms
        "diagnosis": {"english": "diagnosis", "pronunciation": "di-ag-no-sis", "category": "medical", "example": "Diagnosis dokter akurat."},
        "prognosis": {"english": "prognosis", "pronunciation": "prog-no-sis", "category": "medical", "example": "Prognosis pasien baik."},
        "terapi": {"english": "therapy", "pronunciation": "te-ra-pi", "category": "medical", "example": "Terapi fisik efektif."},
        "rehabilitasi": {"english": "rehabilitation", "pronunciation": "re-ha-bi-li-ta-si", "category": "medical", "example": "Rehabilitasi pasien stroke."},
        "operasi": {"english": "surgery", "pronunciation": "o-pe-ra-si", "category": "medical", "example": "Operasi jantung berhasil."},
        "anestesi": {"english": "anesthesia", "pronunciation": "a-nes-te-si", "category": "medical", "example": "Anestesi sebelum operasi."},
        "antibiotik": {"english": "antibiotic", "pronunciation": "an-ti-bi-o-tik", "category": "medical", "example": "Antibiotik lawan bakteri."},
        "vaksin": {"english": "vaccine", "pronunciation": "vak-sin", "category": "medical", "example": "Vaksin cegah penyakit."},
        "imunitas": {"english": "immunity", "pronunciation": "i-mu-ni-tas", "category": "medical", "example": "Imunitas tubuh kuat."},
        "alergi": {"english": "allergy", "pronunciation": "a-ler-gi", "category": "medical", "example": "Alergi makanan laut."},
        "gejala": {"english": "symptom", "pronunciation": "ge-ja-la", "category": "medical", "example": "Gejala flu ringan."},
        "sindrom": {"english": "syndrome", "pronunciation": "sin-drom", "category": "medical", "example": "Sindrom kelelahan."},
        "epidemi": {"english": "epidemic", "pronunciation": "e-pi-de-mi", "category": "medical", "example": "Epidemi flu burung."},
        "pandemi": {"english": "pandemic", "pronunciation": "pan-de-mi", "category": "medical", "example": "Pandemi global."},
        "karantina": {"english": "quarantine", "pronunciation": "ka-ran-ti-na", "category": "medical", "example": "Karantina dua minggu."},
        "isolasi": {"english": "isolation", "pronunciation": "i-so-la-si", "category": "medical", "example": "Isolasi pasien menular."},
        "sterilisasi": {"english": "sterilization", "pronunciation": "ste-ri-li-sa-si", "category": "medical", "example": "Sterilisasi alat medis."},
        "desinfektan": {"english": "disinfectant", "pronunciation": "de-sin-fek-tan", "category": "medical", "example": "Desinfektan bunuh kuman."},
        "patogen": {"english": "pathogen", "pronunciation": "pa-to-gen", "category": "medical", "example": "Patogen penyebab penyakit."},
        "kronik": {"english": "chronic", "pronunciation": "kro-nik", "category": "medical", "example": "Penyakit kronik lama."},
        
        # Advanced Academic Terms
        "akademik": {"english": "academic", "pronunciation": "a-ka-de-mik", "category": "academic", "example": "Prestasi akademik tinggi."},
        "intelektual": {"english": "intellectual", "pronunciation": "in-te-lek-tu-al", "category": "academic", "example": "Diskusi intelektual."},
        "literatur": {"english": "literature", "pronunciation": "li-te-ra-tur", "category": "academic", "example": "Literatur klasik indah."},
        "publikasi": {"english": "publication", "pronunciation": "pub-li-ka-si", "category": "academic", "example": "Publikasi jurnal ilmiah."},
        "disertasi": {"english": "dissertation", "pronunciation": "di-ser-ta-si", "category": "academic", "example": "Disertasi doktor selesai."},
        "tesis": {"english": "thesis", "pronunciation": "te-sis", "category": "academic", "example": "Tesis magister bagus."},
        "skripsi": {"english": "undergraduate thesis", "pronunciation": "skrip-si", "category": "academic", "example": "Skripsi sarjana."},
        "seminar": {"english": "seminar", "pronunciation": "se-mi-nar", "category": "academic", "example": "Seminar nasional."},
        "konferensi": {"english": "conference", "pronunciation": "kon-fe-ren-si", "category": "academic", "example": "Konferensi internasional."},
        "simposium": {"english": "symposium", "pronunciation": "sim-po-si-um", "category": "academic", "example": "Simposium ilmiah."},
        "workshop": {"english": "workshop", "pronunciation": "work-shop", "category": "academic", "example": "Workshop pelatihan."},
        "kurikulum": {"english": "curriculum", "pronunciation": "ku-ri-ku-lum", "category": "academic", "example": "Kurikulum baru efektif."},
        "silabus": {"english": "syllabus", "pronunciation": "si-la-bus", "category": "academic", "example": "Silabus mata kuliah."},
        "kredit": {"english": "credit", "pronunciation": "kre-dit", "category": "academic", "example": "Kredit semester cukup."},
        "indeks": {"english": "index", "pronunciation": "in-deks", "category": "academic", "example": "Indeks prestasi tinggi."},
        "akreditasi": {"english": "accreditation", "pronunciation": "a-kre-di-ta-si", "category": "academic", "example": "Akreditasi universitas A."},
        "sertifikasi": {"english": "certification", "pronunciation": "ser-ti-fi-ka-si", "category": "academic", "example": "Sertifikasi profesi."},
        "kompetensi": {"english": "competency", "pronunciation": "kom-pe-ten-si", "category": "academic", "example": "Kompetensi kerja penting."},
        "kualifikasi": {"english": "qualification", "pronunciation": "kua-li-fi-ka-si", "category": "academic", "example": "Kualifikasi pendidikan."},
        "standar": {"english": "standard", "pronunciation": "stan-dar", "category": "academic", "example": "Standar internasional."}
    }
}
